USE CSoft_Intern_Phonebook_Task1
GO


SELECT * FROM CITIES
GO

SELECT * FROM PHONE_TYPES
GO

SELECT * FROM PERSONS
GO

SELECT * FROM PHONE_NUMBERS
GO

DECLARE @VARNA_CITY_CODE INT
SET @VARNA_CITY_CODE = (SELECT ID FROM CITIES WHERE [NAME] = N'Varna')

/** Who the people from Varna are **/
SELECT
	FIRST_NAME,
	MIDDLE_NAME, 
	LAST_NAME
FROM PERSONS
WHERE CITY_ID = @VARNA_CITY_CODE
GO

DROP VIEW IF EXISTS VI_PERSON_PERSONAL_AND_PHONE_DETAILS
GO

CREATE VIEW VI_PERSON_PERSONAL_AND_PHONE_DETAILS AS
SELECT 
	FIRST_NAME,
	MIDDLE_NAME,
	LAST_NAME,
	CITY_ID,
	PERSON_ID,
	PHONE_TYPE_ID,
	PHONE_NUMBER
FROM PERSONS 
INNER JOIN PHONE_NUMBERS 
	ON PERSONS.ID = PHONE_NUMBERS.PERSON_ID
GO

DECLARE @HOME_ID_CODE INT
SET @HOME_ID_CODE = (SELECT ID FROM PHONE_TYPES WHERE [TYPE] = N'home')

SELECT ID FROM PHONE_TYPES WHERE [TYPE] = N'home'

/** Who the people with home phone numbers are and from where they come **/
SELECT
	FIRST_NAME,
	MIDDLE_NAME,
	LAST_NAME,
	[NAME]
FROM VI_PERSON_PERSONAL_AND_PHONE_DETAILS
INNER JOIN CITIES
	ON VI_PERSON_PERSONAL_AND_PHONE_DETAILS.CITY_ID = CITIES.ID
WHERE PHONE_TYPE_ID = @HOME_ID_CODE
GO

/** People without phone numbers **/
SELECT 
	FIRST_NAME,
	MIDDLE_NAME,
	LAST_NAME
FROM PHONE_NUMBERS
LEFT JOIN PERSONS
	ON PERSONS.ID = PHONE_NUMBERS.PERSON_ID
WHERE PHONE_NUMBER = NULL
GO

/** People with mobile phone numbers and what they are **/
SELECT
	FIRST_NAME,
	MIDDLE_NAME,
	LAST_NAME,
	PHONE_NUMBER
FROM PERSONS
FULL OUTER JOIN PHONE_NUMBERS
	ON PERSONS.ID = PHONE_NUMBERS.PERSON_ID
FULL OUTER JOIN PHONE_TYPES
	ON PHONE_NUMBERS.PHONE_TYPE_ID = PHONE_TYPES.ID
WHERE [TYPE] = N'mobile'
GO

/** From which type phone numbers there are no existing numbers **/
SELECT
	[TYPE]
FROM PHONE_NUMBERS
LEFT JOIN PHONE_TYPES
	ON PHONE_NUMBERS.PHONE_TYPE_ID = PHONE_TYPES.ID
WHERE PHONE_NUMBER = NULL
GO

DECLARE @MILENA_ID_CODE INT
SET @MILENA_ID_CODE = (SELECT ID FROM PERSONS WHERE UCN = N'9507130809')

/** The phone numbers of Milena and of what type they are **/
SELECT
	PHONE_NUMBER,
	[TYPE]
FROM PHONE_NUMBERS
LEFT JOIN PHONE_TYPES
	ON PHONE_NUMBERS.PHONE_TYPE_ID = PHONE_TYPES.ID
WHERE PERSON_ID = @MILENA_ID_CODE
GO

/** The people names and from which city they are - aiming to see from which cities there are no people in the phone book **/
SELECT
	FIRST_NAME,
	MIDDLE_NAME,
	LAST_NAME,
	NAME,
	REGION
FROM PERSONS
RIGHT JOIN CITIES
	ON PERSONS.CITY_ID = CITIES.ID
GO

SELECT
	PERSON_ID,
	PHONE_NUMBER
FROM PHONE_TYPES
FULL OUTER JOIN PHONE_NUMBERS
	ON PHONE_TYPES.ID = PHONE_NUMBERS.PHONE_TYPE_ID
WHERE [TYPE] = N'mobile'
GO

/** Which is the last value from the Identity column in the PERSONS table **/
SELECT MAX(ID) FROM PERSONS